#!/bin/bash

# X number of nodes with Y number of
# cores in each node.
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --mem=2g
#SBATCH --gres=gpu:1

# Partition: cpu | ug-gpu-small
#SBATCH -p ug-gpu-small

# QOS: debug | short | long-high-prio | long-low-prio | long-cpu
#SBATCH --qos=long-low-prio

# TIME(168=7 days)
#SBATCH -t 24:00:00

# Source the bash profile (required to use the module command)
source /etc/profile

# Run your program (replace this with your program)
python3 DL_elmo.py
